# -*- coding: utf-8 -*-
"""hostal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WxE990f3npGdX4ps94apKNg_F0YQd5c
"""

!pip install -U langchain langchain-community langchain-openai langchain-text-splitters faiss-cpu

import os
import time
from google.colab import userdata

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings, ChatOpenAI

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

os.environ["OPENAI_API_KEY"] = userdata.get("GITHUB_TOKEN")
os.environ["OPENAI_BASE_URL"] = userdata.get("GITHUB_BASE_URL")

llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.3
)

print("Modelo cargado")

documents = [
    "El hostal cuenta con habitaciones individuales, dobles y compartidas.",
    "El check-in se realiza desde las 14:00 horas y el check-out hasta las 11:00 horas.",
    "El hostal ofrece WiFi gratuito en todas sus instalaciones.",
    "No se permiten mascotas dentro del hostal.",
    "El desayuno está incluido en el precio de la habitación.",
    "Las reservas pueden cancelarse sin costo hasta 24 horas antes.",
    "El hostal está ubicado en el centro de la ciudad, cerca de transporte público.",
    "Las habitaciones incluyen baño privado y limpieza diaria.",
    "Se puede pagar con tarjeta o efectivo.",
    "Recepción disponible 24 horas.",
    "se dispone de helipuerto para submarinos"
]


splitter = RecursiveCharacterTextSplitter(
    chunk_size=100,
    chunk_overlap=20
)

docs = splitter.create_documents(documents)
print(f"{len(docs)} chunks creados")


embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vector_db = FAISS.from_documents(docs, embeddings)
retriever = vector_db.as_retriever(search_kwargs={"k": 3})

print("Base vectorial lista")

prompt = ChatPromptTemplate.from_messages([
    ("system",
     "Eres un asistente virtual del Hostal Urbano. "
     "Tu función es responder consultas de huéspedes de forma clara, amable y precisa. "
     "SOLO puedes responder utilizando el contexto proporcionado. "
     "Si la información no está en el contexto, indica educadamente que no dispones de esa información "
     "y sugiere contactar a recepción. No inventes información."
    ),
    ("human",
     "Contexto:\n{context}\n\nPregunta:\n{question}"
    )
])

def format_docs(docs):
    return "\n\n".join([d.page_content for d in docs])

rag_chain = (
    {"context": retriever | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
)

print("Pipeline RAG listo")

def rag_hostal(query):
    try:
        start = time.time()

        response = rag_chain.invoke(query)

        end = time.time()

        return {
            "respuesta": response.content,
            "latencia_ms": (end - start) * 1000
        }

    except Exception as e:
        return {"error": str(e)}

print("\nSistema Hostal listo. Escribe 'salir' para terminar.\n")

while True:
    print("\n======================")
    query = input("Pregunta: ")

    if query.lower() == "salir":
        print("Fin del sistema")
        break

    result = rag_hostal(query)

    if "error" in result:
        print("Error:", result["error"])
    else:
        print("\nRespuesta:")
        print(result["respuesta"])